baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Ryan Rinaldi'
theme = 'LoveIt'
paginate = 8

[author]
    name = "Ryan Rinaldi"
    email = "ryan@ryanrinaldi.com"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[params]
    # site default theme ["auto", "light", "dark"]
    defaultTheme = "auto"
    # public git repo url only then enableGitInfo is true
    gitRepo = ""
    # LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
    # ["sha256", "sha384", "sha512", "md5"]
    fingerprint = ""
    # LoveIt NEW | 0.2.0 date format
    dateFormat = "2006-01-02"
    # website title for Open Graph and Twitter Cards
    title = "Ryan Rinaldi"
    # website description for RSS, SEO, Open Graph and Twitter Cards
    description = "Fixing bugs, writing code and helping people since 2000"
    # website images for Open Graph and Twitter Cards
    images = ["/img/cartoon-avatar.jpg"]

 # Header config
[params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
      # URL of the LOGO
      logo = ""
      # title name
      name = ""
      # you can add extra information before the name (HTML format is supported), such as icons
      pre = ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post = ""
      # LoveIt NEW | 0.2.5 whether to use typeit animation for title name
      typeit = false

[params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
    [params.home.profile]
      enable = true
      # Gravatar Email for preferred avatar in home page
      gravatarEmail = ""
      # URL of avatar shown in home page
      avatarURL = "/img/cartoon-avatar.jpg"
      # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      title = "Ryan Rinaldi"
      # subtitle shown in home page (HTML format is supported)
      subtitle = "Professional tech and people leader fueled by iced coffee and sarcasm."
      # whether to use typeit animation for subtitle
      typeit = true
      # whether to show social links
      social = true
      # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      disclaimer = ""

# Social config about the author
  [params.social]
    GitHub = "rrinaldi"
    Linkedin = "ryanrinaldi"
    Twitter = "rrinaldi"
    Instagram = ""
    Facebook = ""
    Telegram = ""
    Medium = ""
    Gitlab = ""
    Youtubelegacy = ""
    Youtubecustom = ""
    Youtubechannel = ""
    Tumblr = ""
    Quora = ""
    Keybase = ""
    Pinterest = ""
    Reddit = ""
    Codepen = ""
    FreeCodeCamp = ""
    Bitbucket = ""
    Stackoverflow = ""
    Weibo = ""
    Odnoklassniki = ""
    VK = ""
    Flickr = ""
    Xing = ""
    Snapchat = ""
    Soundcloud = ""
    Spotify = ""
    Bandcamp = ""
    Paypal = ""
    Fivehundredpx = ""
    Mix = ""
    Goodreads = ""
    Lastfm = ""
    Foursquare = ""
    Hackernews = ""
    Kickstarter = ""
    Patreon = ""
    Steam = ""
    Twitch = ""
    Strava = ""
    Skype = ""
    Whatsapp = ""
    Zhihu = ""
    Douban = ""
    Angellist = ""
    Slidershare = ""
    Jsfiddle = ""
    Deviantart = ""
    Behance = ""
    Dribbble = ""
    Wordpress = ""
    Vine = ""
    Googlescholar = ""
    Researchgate = ""
    Mastodon = "https://fosstodon.org/@rrinaldi"
    Thingiverse = ""
    Devto = ""
    Gitea = ""
    XMPP = ""
    Matrix = ""
    Bilibili = ""
    Discord = ""
    DiscordInvite = ""
    Lichess = ""
    ORCID = ""
    Pleroma = ""
    Kaggle = ""
    MediaWiki= ""
    Plume = ""
    HackTheBox = ""
    RootMe= ""
    Phone = ""
    Email = ""
    RSS = true # LoveIt NEW | 0.2.0
    Threads = "@atrrinaldi"
